### ISSUE TITLE
Add personal image field to the signup page

### ISSUE THREAD

**Issue by Yassa-hue** [Yassa-hue/graduation-project-flutter#27]
## What to do:
Add an image picker input field to the sign up page so that the user can upload his personal image.

## Notes for the dev:
Note that the file name is updated to `user_form_page.dart`!
Note that the default image is the image stored in the user model object if not null!

**Comment by ihab4real** [comment]
add an input field in the same signup page? this is not common

**Comment by Yassa-hue** [comment]
It's just a demo app + it is easier.

**Comment by ihab4real** [comment]
you're the boss
